# maximum number of iterations
maxIter: 50
# initial trust region radius
r0: 1e2
# stopping tolerance for the change of the convex cost
dLTol: 1e-2
# similarity metric thresholds
rho0: 0.0
rho1: 0.25
rho2: 0.90
# trust-region expand and shrink factors
beta_expand: 3.2
beta_shrink: 2.0
# trust-region radius limits
rMin: 1e-3
rMax: 1e3
